### ISSUE TITLE
修复一下iOS16的兼容性问题

### ISSUE THREAD

**Issue by ngfdCuteMetro** [hqy2000/EMURoutingTracker#1]
iOS端在升级iOS16系统后无法进行扫码，希望能修复一下

**Comment by ngfdCuteMetro** [comment]
iOS端升级iOS16后无法进入扫描二维码的界面，希望能修复一下

**Comment by hqy2000** [comment]
感谢反馈，已经修复 https://github.com/hqy2000/EMURoutingTracker/commit/65727bacd19589e3a2fda02543ad38372d116601

**Comment by hqy2000** [comment]
已经提交 app store，请留意近期更新
