### ISSUE TITLE
车组查询的原网站貌似以停用

### ISSUE THREAD

**Issue by ngfdCuteMetro** [hqy2000/EMURoutingTracker#3]
APP绑定的https://moerail.mirrors.tk/这个网站貌似不能用了，rail.re是新网站，可以去更换一下这个新域名

**Comment by dnyBLUESKY007** [comment]
遇到了同样的问题，做点补充：fork下来源码build到设备上能够正常查询到车组信息，但App Store版本提示"URLSessionTask failed with error: An SSL error has occurred and a secure connection to the server cannot be made."，发着查询中所有担当车组均为未知。对比了一下源码build的版本（rail.re，但app内显示为rail.rl）和App Store的版本发现数据来源处不同。

**Comment by hqy2000** [comment]
很早之前就已经修改了。改完结果把去 App Store 更新版本这事给忘了😂。现在已经提交更新了，过几天应该就能看到了。
