### ISSUE TITLE
关于App Store无法安装

### ISSUE THREAD

**Issue by su2018** [hqy2000/EMURoutingTracker#5]
你好，我使用国区/美区/法区三地账号均提示：APP不可用，目前你所在国家或地区尚不提供此APP，请问，需要使用哪个地区的账号进行下载及安装，谢谢

**Comment by Hanson-hzc** [comment]
同问

**Comment by su2018** [comment]
您好，我会尽快查阅并回复您的邮件。

**Comment by Hanson-hzc** [comment]
貌似被全区下架了

**Comment by hqy2000** [comment]
抱歉，因为 Apple Developer 自动续费没有成功被下架了，现在已经恢复了
